# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  app-hub-image-name: 'dxapphub:$(build.buildId)'

jobs: 
  - job: build_app_hub
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: docker build -f Dockerfile -t $(app-hub-image-name) ./app-hub-gui/
      displayName: 'docker build'
    - script: mkdir "publish" && docker save $(app-hub-image-name) > ./publish/$(app-hub-image-name).tar
      displayName: 'save docker image'
    - task: PublishPipelineArtifact@0
      inputs: 
        artifactName: 'testImage'
        targetPath: './publish'
  - job: loading_image
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn: build_app_hub
    steps:
      - task: DownloadPipelineArtifact@0
        inputs: 
          targetPath: .
          artifactName: 'testImage'
      - script: docker load < $(app-hub-image-name).tar
        displayName: 'Loading Docker Image'
