# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


variables:
  imageName: 'dxapphub:$(build.buildId)'

jobs: 
  - job: build_image
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: docker build -f Dockerfile -t $(imageName) .
      displayName: 'docker build'
    - script: mkdir "publish" && docker save $(imageName) > ./publish/$(imageName.tar)
      displayName: 'save docker image'
    - task: PublishPipelineArtifact@0
      inputs: 
        artifactName: 'testImage'
        targetPath: './publish'
  - job: a11y_test
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: DownloadPipelineArtifact@0
        inputs: 
          targetPath: .
          artifactName: 'testImage'

