# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  app-hub-gui-image-name: 'dxapphubgui:$(build.buildId)'
  app-hub-api-image-name: 'dxapphubapi:$(build.buildId)'

jobs: 
  - job: build_app_hub_gui
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: docker build -f ./app-hub-gui/Dockerfile -t $(app-hub-gui-image-name) ./app-hub-gui/
    - script: docker build -f Dockerfile -t $(app-hub-gui-image-name) ./app-hub-gui/
      displayName: 'docker build'
    - script: mkdir "publish" && docker save $(app-hub-gui-image-name) > ./publish/$(app-hub-gui-image-name).tar
      displayName: 'save docker image'
    - task: PublishPipelineArtifact@0
      inputs: 
        artifactName: '$(app-hub-gui-image-name)'
        targetPath: './publish'
  - job: build_app_hub_api
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: docker build -f ./app-hub-api/Dockerfile -t $(app-hub-api-image-name) ./app-hub-api/
    - script: docker build -f Dockerfile -t $(app-hub-api-image-name) ./app-hub-api/
      displayName: 'docker build'
    - script: mkdir "publish" && docker save $(app-hub-api-image-name) > ./publish/$(app-hub-api-image-name).tar
      displayName: 'save docker image'
    - task: PublishPipelineArtifact@0
      inputs: 
        artifactName: '$(app-hub-api-image-name)'
        targetPath: './publish'
  - job: loading_image
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn: 
      - build_app_hub_gui 
      - build_app_hub_api
    steps:
      - task: DownloadPipelineArtifact@0
        inputs: 
          targetPath: .
          artifactName: '$(app-hub-gui-image-name)'
      - task: DownloadPipelineArtifact@0
        inputs: 
          targetPath: .
          artifactName: '$(app-hub-api-image-name)'
      - script: docker load < $(app-hub-gui-image-name).tar
        displayName: 'Loading Docker Image'
      - script: docker load < $(app-hub-api-image-name).tar
        displayName: 'Loading Docker Image'
